TestingAppQa/Controllers/TestCasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestingAppQa.Data;
using TestingAppQa.Models;

namespace TestingAppQa.Controllers
{
    public class TestCasesController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<User> _userManager;

        public TestCasesController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: TestCases
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            List<TestCase> testCases = await (from a in _context.TestCase
                                              where a.HistoryUser.IdUserHistory == user.IdHUActive
                                              select a).ToListAsync();
            //var data = await _context.Project.ToListAsync();
            return View(testCases);
        }

        // GET: TestCases/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testCase = await _context.TestCase
                .FirstOrDefaultAsync(m => m.IdTestCase == id);
            if (testCase == null)
            {
                return NotFound();
            }

            return View(testCase);
        }

        // GET: TestCases/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TestCases/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdTestCase,TestType,Var,StepStep,Analyst")] TestCase testCase)
        {
            var user = await _userManager.GetUserAsync(User);
            var hu = _context.UserHistory.Find(user.IdHUActive);
            testCase.HistoryUser = hu;
            if (ModelState.IsValid)
            {
                _context.TestCase.Add(testCase);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(testCase);
        }

        // GET: TestCases/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testCase = await _context.TestCase.FindAsync(id);
            if (testCase == null)
            {
                return NotFound();
            }
            return View(testCase);
        }

        // POST: TestCases/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdTestCase,TestType,Var,StepStep,Analyst")] TestCase testCase)
        {
            if (id != testCase.IdTestCase)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(testCase);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TestCaseExists(testCase.IdTestCase))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(testCase);
        }

        // GET: TestCases/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testCase = await _context.TestCase
                .FirstOrDefaultAsync(m => m.IdTestCase == id);
            if (testCase == null)
            {
                return NotFound();
            }

            return View(testCase);
        }

        // POST: TestCases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var testCase = await _context.TestCase.FindAsync(id);
            _context.TestCase.Remove(testCase);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TestCaseExists(int id)
        {
            return _context.TestCase.Any(e => e.IdTestCase == id);
        }
    }
}

TestingAppQa/Views/TestCases/Create.cshtml
@model TestingAppQa.Models.TestCase

@{
    ViewData["Title"] = "Create";
    Layout = null;
}
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="modal-body">
                <label asp-for="TestType" class="control-label">Tipo De Prueba</label>
                <input asp-for="TestType" class="form-control" />
                <span asp-validation-for="TestType" class="text-danger"></span>

                <label asp-for="Var" class="control-label">Variable</label>
                <input asp-for="Var" class="form-control" />
                <span asp-validation-for="Var" class="text-danger"></span>

                <label asp-for="StepStep" class="control-label">Paso a Paso</label>
                <input asp-for="StepStep" class="form-control" />
                <span asp-validation-for="StepStep" class="text-danger"></span>

                <label asp-for="Analyst" class="control-label">Analista Encargado</label>
                <input asp-for="Analyst" class="form-control" />
                <span asp-validation-for="Analyst" class="text-danger"></span>
            </div>
            <div class=" d-flex justify-content-between p-2 form-group">
                <div>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Confirmar</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestingAppQa/Views/TestCases/Delete.cshtml
@model TestingAppQa.Models.TestCase

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Estas seguro que quieres eliminar este caso de prueba?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <label asp-for="TestType" class="control-label">Tipo de test</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TestType)
        </dd>
        <dt class="col-sm-2">
            <label asp-for="Var" class="control-label">Variable</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Var)
        </dd>
        <dt class="col-sm-2">
            <label asp-for="StepStep" class="control-label">Paso a Paso</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StepStep)
        </dd>
        <dt class="col-sm-2">
            <label asp-for="Analyst" class="control-label">Analista Encargado</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Analyst)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdTestCase" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a lista de Casos de prueba</a>
    </form>
</div>

TestingAppQa/Views/TestCases/Details.cshtml
@model TestingAppQa.Models.TestCase

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>TestCase</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TestType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TestType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Var)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Var)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StepStep)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StepStep)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Analyst)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Analyst)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdTestCase">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TestingAppQa/Views/TestCases/Edit.cshtml
@model TestingAppQa.Models.TestCase

@{
    ViewData["Title"] = "Editar";
    Layout = null;
}
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="modal-body">
                <input type="hidden" asp-for="IdTestCase" />
                <label asp-for="TestType" class="control-label">Tipo de prueba</label>
                <input asp-for="TestType" class="form-control" />
                <span asp-validation-for="TestType" class="text-danger"></span>

                <label asp-for="Var" class="control-label">Variable</label>
                <input asp-for="Var" class="form-control" />
                <span asp-validation-for="Var" class="text-danger"></span>

                <label asp-for="StepStep" class="control-label">Paso a Paso</label>
                <input asp-for="StepStep" class="form-control" />
                <span asp-validation-for="StepStep" class="text-danger"></span>

                <label asp-for="Analyst" class="control-label">Analista</label>
                <input asp-for="Analyst" class="form-control" />
                <span asp-validation-for="Analyst" class="text-danger"></span>

            </div>
            <div class=" d-flex justify-content-between p-2 form-group">
                <div>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Confirmar</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestingAppQa/Views/TestCases/Index.cshtml
@model IEnumerable<TestingAppQa.Models.TestCase>

<div class="content">
    <div class="d-flex justify-content-between">
        <!-- Animated -->
        <h3 class="text-secondary">Casos de Prueba</h3>

        <a onclick="showInPopup('@Url.Action("Create", "TestCases", null,Context.Request.Scheme)', 'Caso de prueba Nuevo')" class="btn btn-danger text-white"><i class="fa fa-plus"></i>Nuevo caso de prueba</a>

    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body ">


                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th class="serial">Tipo de Prueba</th>
                                    <th class="avatar">Variable</th>
                                    <th>Paso A Paso</th>
                                    <th>Analista Encargado</th>
                                    <th>Acción</th>
                                </tr>
                            </thead>
                            <tbody>


                                @foreach (var item in Model)
                                {
                                <tr>

                                    <td class="serial">@Html.DisplayFor(modelItem => item.TestType)</td>
                                    <td class="serial">@Html.DisplayFor(modelItem => item.Var)</td>
                                    <td class="serial">@Html.DisplayFor(modelItem => item.StepStep)</td>
                                    <td class="serial">@Html.DisplayFor(modelItem => item.Analyst)</td>
                                    <td class="serial">
                                        <a>
                                            <i class="fa fa-pencil" onclick="showInPopup('@Url.Action("Edit","TestCases",new {id=item.IdTestCase},Context.Request.Scheme)','Modificar Informacion General Del Caso de Prueba')" class="fa fa-pencil p-2">
                                            </i>
                                        </a>
                                        <a asp-action="Delete" asp-route-id="@item.IdTestCase"><i class="fa fa-trash"></i></a>

                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div><!-- /# column -->


    </div>
    <!-- .animated -->
</div>
@section scripts{
    <script src="~/js/modales/modales.js"></script> }