TestingAppQa/Models/Scope.cs
using System.ComponentModel.DataAnnotations;

namespace TestingAppQa.Models
{
    public class Scope
    {
        [Key]
        public int IdScope { get; set; }

        public string NameModule { get; set; }

        public string TestGoal { get; set; }
        public string Considerations { get; set; }

        public UserHistory UserHistory { get; set; }
    }
}

TestingAppQa/Controllers/ScopesController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestingAppQa.Data;
using TestingAppQa.Models;

namespace TestingAppQa.Controllers
{
    public class ScopesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public ScopesController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Scopes
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            List<Scope> scopes = await (from a in _context.Scope
                                              where a.UserHistory.IdUserHistory == user.IdHUActive
                                              select a).ToListAsync();
            return View(scopes);
        }

        // GET: Scopes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scope = await _context.Scope
                .FirstOrDefaultAsync(m => m.IdScope == id);
            if (scope == null)
            {
                return NotFound();
            }

            return View(scope);
        }

        // GET: Scopes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Scopes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdScope,NameModule,TestGoal,Considerations")] Scope scope)
        {
            var user = await _userManager.GetUserAsync(User);
            UserHistory project = await (from a in _context.UserHistory
                                         where a.IdUserHistory == user.IdHUActive && a.IsDeleted == false
                                         select a).FirstOrDefaultAsync();
            scope.UserHistory = project;
            if (ModelState.IsValid)
            {
                _context.Add(scope);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(scope);
        }

        // GET: Scopes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scope = await _context.Scope.FindAsync(id);
            if (scope == null)
            {
                return NotFound();
            }
            return View(scope);
        }

        // POST: Scopes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,[Bind("IdScope,NameModule,TestGoal,Considerations")] Scope scope)
        {
            if (id != scope.IdScope)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(scope);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScopeExists(scope.IdScope))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(scope);
        }

        // GET: Scopes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var scope = await _context.Scope
                .FirstOrDefaultAsync(m => m.IdScope == id);
            if (scope == null)
            {
                return NotFound();
            }

            return View(scope);
        }

        // POST: Scopes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var scope = await _context.Scope.FindAsync(id);
            _context.Scope.Remove(scope);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ScopeExists(int id)
        {
            return _context.Scope.Any(e => e.IdScope == id);
        }
    }
}

TestingAppQa/Views/Scopes/Create.cshtml
@model TestingAppQa.Models.Scope

@{
    ViewData["Title"] = "Create";
    Layout = null;
}
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="modal-body">
                <label asp-for="NameModule" class="control-label">Nombre del modulo</label>
                <input asp-for="NameModule" class="form-control" />
                <span asp-validation-for="NameModule" class="text-danger"></span>
                <label asp-for="TestGoal" class="control-label">Objetivo de la prueba</label>
                <input asp-for="TestGoal" class="form-control" />
                <span asp-validation-for="TestGoal" class="text-danger"></span>
                <label asp-for="Considerations" class="control-label">Consideraciones</label>
                <input asp-for="Considerations" class="form-control" />
                <span asp-validation-for="Considerations" class="text-danger"></span>
            </div>
            <div class=" d-flex justify-content-between p-2 form-group">
                <div>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Confirmar</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestingAppQa/Views/Scopes/Delete.cshtml
@model TestingAppQa.Models.Scope

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h3>¿Estas Seguro de quieres borrar este alcance?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <label asp-for="NameModule" class="control-label">Nombre Modulo</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameModule)
        </dd>
        <dt class="col-sm-2">
            <label asp-for="Considerations" class="control-label">Consideraciones</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Considerations)
        </dd>
        <dt class="col-sm-2">
            <label asp-for="TestGoal" class="control-label">Objetivo de la prueba</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TestGoal)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdScope" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a la lista de alcances</a>
    </form>
</div>

TestingAppQa/Views/Scopes/Details.cshtml
@model TestingAppQa.Models.Scope

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Scope</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameModule)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameModule)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameModule)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameModule)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameModule)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameModule)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdScope">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TestingAppQa/Views/Scopes/Edit.cshtml
@model TestingAppQa.Models.Scope

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="modal-body">
                <input type="hidden" asp-for="IdScope" />
                <label asp-for="NameModule" class="control-label">Nombre modulo</label>
                <input asp-for="NameModule" class="form-control" />
                <span asp-validation-for="NameModule" class="text-danger"></span>
                <label asp-for="Considerations" class="control-label">Consideraciones</label>
                <input asp-for="Considerations" class="form-control" />
                <span asp-validation-for="Considerations" class="text-danger"></span>
                <label asp-for="TestGoal" class="control-label">Objetivo</label>
                <input asp-for="TestGoal" class="form-control" />
                <span asp-validation-for="TestGoal" class="text-danger"></span>
            </div>
            <div class=" d-flex justify-content-between p-2 form-group">
                <div>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Confirmar</button>

                </div>
            </div>

        </form>
        <form asp-controller="Scopes" asp-action="Delete" asp-route-id="@Model.IdScope" method="post" style="display:inline;">
            <button type="submit" class="btn btn-warning" onclick="return confirm('¿Estás seguro de que deseas eliminar este registro?');">Borrar</button>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TestingAppQa/Views/Scopes/Index.cshtml
@model IEnumerable<TestingAppQa.Models.Scope>

<div class="content">
    <div class="d-flex justify-content-between">
        <!-- Animated -->
        <h3 class="text-secondary">Alcances</h3>

        <a onclick="showInPopup('@Url.Action("Create", "Scopes", null,Context.Request.Scheme)', 'Nuevo Alcance')" class="btn btn-danger text-white"><i class="fa fa-plus"></i>Nuevo Alcance</a>

    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body ">


                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th class="serial">Nombre del Modulo</th>
                                    <th class="avatar">Objetivo de la prueba</th>
                                    <th>Consideraciones</th>
                                    <th>Acción</th>
                                </tr>
                            </thead>
                            <tbody>


                                @foreach (var item in Model)
                                {
                                    <tr>

                                        <td class="serial">@Html.DisplayFor(modelItem => item.NameModule)</td>
                                        <td class="serial">@Html.DisplayFor(modelItem => item.TestGoal)</td>
                                        <td class="serial">@Html.DisplayFor(modelItem => item.Considerations)</td>

                                        <td class="serial">
                                            <a>
                                                <i class="fa fa-pencil" onclick="showInPopup('@Url.Action("Edit","Scopes",new {id=item.IdScope},Context.Request.Scheme)','Modificar Informacion General Del Alcance')" class="fa fa-pencil p-2">
                                                </i>
                                            </a>
                                            <a asp-action="Delete" asp-route-id="@item.IdScope"><i class="fa fa-trash"></i></a>

                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/js/modales/modales.js"></script> }