TestingAppQa/Models/TimeOut.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TestingAppQa.Models
{
    public class TimeOut
    {
        [Key]
        public int IdTimeOut { get; set; }

        public string Name { get; set; }

        public UserHistory Hu { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }
    }
}

TestingAppQa/Controllers/TimeOutsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestingAppQa.Data;
using TestingAppQa.Models;

namespace TestingAppQa.Controllers
{
    public class TimeOutsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;
        public TimeOutsController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: TimeOuts
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user.IdSprintActive != 0)
            {
                List<TimeOut> userHistories = await (from s in _context.TimeOut
                                                         where s.Hu.IdUserHistory == user.IdHUActive
                                                         select s).ToListAsync();
                return View(userHistories);
            }
            else
            {
                return View("SeleccionarProyecto");
            }
        }

        public async Task<List<TimeOut>> getData()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user.IdSprintActive != 0)
            {
                List<TimeOut> userHistories = await (from s in _context.TimeOut
                                                     where s.Hu.IdUserHistory == user.IdHUActive
                                                     select s).ToListAsync();
                return userHistories;
            }
            else
            {
                List<TimeOut> userHistoriesvacia = new List<TimeOut>();
                return userHistoriesvacia;
            }

        }

        // GET: TimeOuts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeOut = await _context.TimeOut
                .FirstOrDefaultAsync(m => m.IdTimeOut == id);
            if (timeOut == null)
            {
                return NotFound();
            }

            return View(timeOut);
        }

        // GET: TimeOuts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TimeOuts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create(string Name, string StartDate ,string EndDate)
        {
            DateTime fechainicio = Convert.ToDateTime(StartDate + " 07:20:20");
            DateTime fechafinal = Convert.ToDateTime(EndDate + " 07:20:20");
            fechainicio =fechainicio.AddDays(1);
            fechafinal = fechafinal.AddDays(1);
            fechainicio.AddHours(2);
            fechafinal.AddHours(3);
            var user = await _userManager.GetUserAsync(User);
            var hu = _context.UserHistory.Find(user.IdHUActive);
            TimeOut timeOut = new TimeOut() { Name = Name , StartDate = fechainicio, EndDate = fechafinal, Hu = hu };
            _context.Add(timeOut);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: TimeOuts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeOut = await _context.TimeOut.FindAsync(id);
            if (timeOut == null)
            {
                return NotFound();
            }
            return View(timeOut);
        }

        // POST: TimeOuts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdTimeOut,Name,StartDate,EndDate")] TimeOut timeOut)
        {
            if (id != timeOut.IdTimeOut)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(timeOut);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TimeOutExists(timeOut.IdTimeOut))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(timeOut);
        }

        // GET: TimeOuts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeOut = await _context.TimeOut
                .FirstOrDefaultAsync(m => m.IdTimeOut == id);
            if (timeOut == null)
            {
                return NotFound();
            }

            return View(timeOut);
        }

        // POST: TimeOuts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var timeOut = await _context.TimeOut.FindAsync(id);
            _context.TimeOut.Remove(timeOut);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TimeOutExists(int id)
        {
            return _context.TimeOut.Any(e => e.IdTimeOut == id);
        }
    }
}

TestingAppQa/Views/TimeOuts/Create.cshtml
@*@model TestingAppQa.Models.Project
    <div class="modal fade" id="addproyect" tabindex="-1" aria-labelledby="nuevoSprint" aria-hidden="true">

        <div class="modal" tabindex="-1" role="dialog" id="form-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title"></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="modal-body">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class=" d-flex justify-content-between p-2 form-group">
                                <div>
                                    <button type="button" class="btn btn-danger">Delete</button>
                                </div>
                                <div>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                    <button type="submit" class="btn btn-success">Confirm</button>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>

    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

@model TestingAppQa.Models.TimeOut

@{
    ViewData["Title"] = "Edit";
    Layout = null;
}


<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="modal-body">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class=" d-flex justify-content-between p-2 form-group">
                <div>
                    <button type="button" class="btn btn-danger">Delete</button>
                </div>
                <div>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-success">Confirmar</button>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestingAppQa/Views/TimeOuts/Delete.cshtml
@model TestingAppQa.Models.TimeOut

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TimeOut</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdTimeOut" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TestingAppQa/Views/TimeOuts/Details.cshtml
@model TestingAppQa.Models.TimeOut

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>TimeOut</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdTimeOut">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TestingAppQa/Views/TimeOuts/Edit.cshtml
@model TestingAppQa.Models.TimeOut

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>TimeOut</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdTimeOut" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TestingAppQa/Views/TimeOuts/Index.cshtml
@model IEnumerable<TestingAppQa.Models.TimeOut>
<div class="content">
    <div class="d-flex justify-content-between">
        <!-- Animated -->
        <h3 class="text-secondary">Tiempos De Salida</h3>
    </div>


    <!-- Header-->
    <!-- /#header -->
    <!-- Content -->
    <div class="content">
        <!-- Animated -->
        <div class="animated fadeIn">
            <!-- Widgets  -->
            <!-- /To Do and Live Chat -->
            <!-- Calender Chart Weather  -->
            <div class="row">
                <div class="col-md-12 col-lg-4">
                    <div class="card">
                        <div class="card-body">
                            <!-- <h4 class="box-title">Chandler</h4> -->
                            <div class="calender-cont widget-calender">
                                <div id="calendar"></div>
                            </div>
                        </div>
                    </div><!-- /.card -->
                </div>
            </div>

            <div class="modal fade none-border" id="event-modal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title"><strong>Agregar Tiempo de salida</strong></h4>
                        </div>
                        <div class="modal-body"></div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-success save-event waves-effect waves-light">Crear Tiempo de salida</button>
                            <button type="button" class="btn btn-danger delete-event waves-effect waves-light" data-dismiss="modal">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Calender Chart Weather -->
            <!-- Modal - Calendar - Add New Event -->
            <!-- /#event-modal -->
            <!-- Modal - Calendar - Add Category -->
            <!-- /#add-category -->
        </div>
        <!-- .animated -->
    </div>
    <!-- /.content -->
    <div class="clearfix"></div>
    <!-- Footer -->
    <!-- /.site-footer -->
</div>
@section scripts{

    <script>
!function($) {
    "use strict";

    var CalendarApp = function() {
        this.$body = $("body")
        this.$modal = $('#event-modal'),
        this.$event = ('#external-events div.external-event'),
        this.$calendar = $('#calendar'),
        this.$saveCategoryBtn = $('.save-category'),
        this.$categoryForm = $('#add-category form'),
        this.$extEvents = $('#external-events'),
        this.$calendarObj = null
    };
    /* on drop */
    CalendarApp.prototype.onDrop = function (eventObj, date) {
        console.log("Entre y guardo 1")
        var $this = this;
            // retrieve the dropped element's stored Event Object
            var originalEventObject = eventObj.data('eventObject');
            var $categoryClass = eventObj.attr('data-class');
            // we need to copy it, so that multiple events don't have a reference to the same object
            var copiedEventObject = $.extend({}, originalEventObject);
            // assign it the date that was reported
            copiedEventObject.start = date;
            if ($categoryClass)
                copiedEventObject['className'] = [$categoryClass];
            // render the event on the calendar
            $this.$calendar.fullCalendar('renderEvent', copiedEventObject, true);
            // is the "remove after drop" checkbox checked?
            if ($('#drop-remove').is(':checked')) {
                // if so, remove the element from the "Draggable Events" list
                eventObj.remove();
            }
    },
    /* on click on event */
        CalendarApp.prototype.onEventClick = function (calEvent, jsEvent, view) {
        console.log("Entre y guardo2")
        var $this = this;
            var form = $("<form></form>");
            form.append("<label>Change event name</label>");
            form.append("<div class='input-group'><input class='form-control' type=text value='" + calEvent.title + "' /><span class='input-group-btn'><button type='submit' class='btn btn-success waves-effect waves-light'><i class='fa fa-check'></i> Save</button></span></div>");
            $this.$modal.modal({
                backdrop: 'static'
            });
            $this.$modal.find('.delete-event').show().end().find('.save-event').hide().end().find('.modal-body').empty().prepend(form).end().find('.delete-event').unbind('click').click(function () {
                $this.$calendarObj.fullCalendar('removeEvents', function (ev) {
                    console.log("Entre y guardo 3")
                    return (ev._id == calEvent._id);
                });
                $this.$modal.modal('hide');
            });
        $this.$modal.find('form').on('submit', function () {
            console.log("Entre y guardo 4")
                calEvent.title = form.find("input[type=text]").val();
                $this.$calendarObj.fullCalendar('updateEvent', calEvent);
                $this.$modal.modal('hide');
                return false;
            });
    },
    /* on select */
        CalendarApp.prototype.onSelect = function (start, end, allDay) {

        var $this = this;
            $this.$modal.modal({
                backdrop: 'static'
            });
            var form = $("<form></form>");
            form.append("<div class='row'></div>");
            form.find(".row")
                .append("<div class='col-md-6'><div class='form-group'><label class='control-label'>Event Name</label><input class='form-control' placeholder='Insert Event Name' type='text' name='title'/></div></div>")
                        .append("<div class='col-md-6'><div class='form-group'><label class='control-label'></label><select hidden class='form-control' name='category'></select></div></div>")
                .find("select[name='category']")
                .append("<option value='bg-danger'>Danger</option>")
                .append("<option value='bg-success'>Success</option>")
                .append("<option value='bg-dark'>Dark</option>")
                .append("<option value='bg-primary'>Primary</option>")
                .append("<option value='bg-pink'>Pink</option>")
                .append("<option value='bg-info'>Info</option>")
                .append("<option value='bg-warning'>Warning</option></div></div>");
            $this.$modal.find('.delete-event').hide().end().find('.save-event').show().end().find('.modal-body').empty().prepend(form).end().find('.save-event').unbind('click').click(function () {
                form.submit();
            });
        $this.$modal.find('form').on('submit', function () {

                var title = form.find("input[name='title']").val();
                var beginning = form.find("input[name='beginning']").val();
                var ending = form.find("input[name='ending']").val();
                var categoryClass = form.find("select[name='category'] option:checked").val();
                if (title !== null && title.length != 0) {
                    $this.$calendarObj.fullCalendar('renderEvent', {
                        title: title,
                        start:start,
                        end: end,
                        allDay: false,
                        className: categoryClass
                    }, true);
                    $this.$modal.modal('hide');
                }
                else{
                    alert('You have to give a title to your event');
            }

            $.post("@Url.Action("Create", "TimeOuts")?Name=" + title + "&StartDate=" + start._d.toLocaleDateString() + "&EndDate=" + end._d.toLocaleDateString(),function(re){

         //redirect now

     });
                return false;

            });
        $this.$calendarObj.fullCalendar('unselect');
    },
        CalendarApp.prototype.enableDrag = function () {
        console.log("Entre y guardo 7")
        //init events
        $(this.$event).each(function () {
            console.log("Entre y guardo 8")
            // create an Event Object (http://arshaw.com/fullcalendar/docs/event_data/Event_Object/)
            // it doesn't need to have a start or end
            var eventObject = {
                title: $.trim($(this).text()) // use the element's text as the event title
            };
            // store the Event Object in the DOM element so we can get to it later
            $(this).data('eventObject', eventObject);
            // make the event draggable using jQuery UI
            $(this).draggable({
                zIndex: 999,
                revert: true,      // will cause the event to go back to its
                revertDuration: 0  //  original position after the drag
            });
        });
    }
    /* Initializing */
    CalendarApp.prototype.init = function () {
        console.log("Entre y guardo 9")
        this.enableDrag();
        /*  Initialize the calendar  */
        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();
        var form = '';
        var today = new Date($.now());
        @*$.get("@Url.Action("Create", "TimeOuts")?Name=" + title + "&StartDate=" + start._d.toLocaleDateString() + "&EndDate=" + end._d.toLocaleDateString(),function(re){

         //redirect now
            var $this = this;
        });*@
        var $this = this;
        const claus = ["bg-dark", "bg-danger", "bg-primary"];
        var data = $.get("@Url.Action("getData", "TimeOuts")", function (data, status) {
            var datameets = data.map((x) => {
                return { title: x.name, start: new Date(x.startDate), end: new Date(x.endDate), className: claus[Math.floor(Math.random() * claus.length)] }
            })
            console.log(datameets);
            $this.$calendarObj = $this.$calendar.fullCalendar({
                slotDuration: '00:15:00', /* If we want to split day time each 15minutes */
                minTime: '08:00:00',
                maxTime: '19:00:00',
                defaultView: 'month',
                handleWindowResize: true,
                height: $(window).height() - 200,
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                events: datameets,
                editable: true,
                droppable: true, // this allows things to be dropped onto the calendar !!!
                eventLimit: true, // allow "more" link when too many events
                selectable: true,
                drop: function (date) { $this.onDrop($(this), date); },
                select: function (start, end, allDay) { $this.onSelect(start, end, allDay); },
                eventClick: function (calEvent, jsEvent, view) { $this.onEventClick(calEvent, jsEvent, view); }

            });
        });




        //on new event
        this.$saveCategoryBtn.on('click', function () {
            console.log("Entre y guardo 10")
            var categoryName = $this.$categoryForm.find("input[name='category-name']").val();
            var categoryColor = $this.$categoryForm.find("select[name='category-color']").val();
            if (categoryName !== null && categoryName.length != 0) {
                $this.$extEvents.append('<div class="external-event bg-' + categoryColor + '" data-class="bg-' + categoryColor + '" style="position: relative;"><i class="fa fa-move"></i>' + categoryName + '</div>')
                $this.enableDrag();
            }

        });
    },

   //init CalendarApp
    $.CalendarApp = new CalendarApp, $.CalendarApp.Constructor = CalendarApp

}(window.jQuery),

//initializing CalendarApp
function($) {
    "use strict";
    $.CalendarApp.init()
            }(window.jQuery);

    </script>
}

TestingAppQa/Views/TimeOuts/SeleccionarProyecto.cshtml
    <div class="content">
        <div class="d-flex justify-content-between">
            <!-- Animated -->
            <h3 class="text-secondary">Por Favor Selecciona un Ambito de Proyecto desde la opcion de proyectos</h3>

        </div>
        <!-- .animated -->
    </div>
    @section scripts{
    <script src="~/js/modales/modales.js"></script> }